version: '3.8'

services:
  # Serviço da Aplicação (API)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-api-gestao-competicoes
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '1.0'
    environment:
      # Conexão com o serviço 'db' definido abaixo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-gestao-competicoes:5432/gestao_competicoes_db
      SPRING_DATASOURCE_USERNAME: admin_esportes
      SPRING_DATASOURCE_PASSWORD: senha_segura_123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      # Logs e Arquivos no Host
      - ./infra/logs:/app/logs
      - ./infra/data:/app/data
    networks:
      - rede_esportes_dev

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:17.0
    container_name: db-gestao-competicoes
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      POSTGRES_DB: gestao_competicoes_db
      POSTGRES_USER: admin_esportes
      POSTGRES_PASSWORD: senha_segura_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_esportes_dev

volumes:
  postgres_data:

networks:
  rede_esportes_dev:
    driver: bridge